# Generated by Django 3.0.7 on 2020-06-21 19:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Slot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, default=None, editable=False, null=True, verbose_name='Deleted At')),
                ('number', models.PositiveSmallIntegerField(verbose_name='Number')),
                ('floor', models.SmallIntegerField(blank=True, default=0, null=True, verbose_name='Floor')),
                ('coords', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'North'), (2, 'North East'), (3, 'East'), (4, 'South East'), (5, 'South'), (6, 'South West'), (7, 'West'), (8, 'North West')], null=True, verbose_name='Coords')),
            ],
            options={
                'verbose_name': 'Slot',
                'verbose_name_plural': 'Slots',
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, default=None, editable=False, null=True, verbose_name='Deleted At')),
                ('plate_number', models.CharField(blank=True, max_length=10, null=True, verbose_name='Plate Number')),
                ('reserved_from', models.DateTimeField(verbose_name='Reserved From')),
                ('reserved_to', models.DateTimeField(verbose_name='Reserved To')),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='reservations', to='api.Slot', verbose_name='Slot')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Reservation',
                'verbose_name_plural': 'Reservations',
                'ordering': ['reserved_from'],
            },
        ),
    ]
